#!/bin/bash

# thumbnails file type and size
THEXT=png
THWID=120
THHEI=90
# thumbnail galery page cols
THCOL=7
# get working directory name
WDNAM=$( basename ${PWD} )
# create galery directory
[ -d ${PWD}/${WDNAM} ] || mkdir ${PWD}/${WDNAM}
# galery index page
GPAGE="${PWD}/${WDNAM}/index.html"
# thumbnails directory
THDIR="${PWD}/${WDNAM}/.tpics"
# default high for resize:
RSHEI=512
# watermark
WMARK="CC.BY"
# galery title
GNAME=${WDNAM}

# check command line options
while getopts ":c:t:m:" opt; do
  case $opt in
    c)
		THCOL=${OPTARG}
      ;;
	 t)
		GNAME=${OPTARG}
		;;
	 m)
		WMARK=${OPTARG}
		;;
    \?)
      echo "Invalid option: -${OPTARG}" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done

# create thumb dir if not exists.
[ -d ${THDIR} ] || mkdir ${THDIR}

# backup GFILE if exists.
[ -w ${GPAGE} ] && mv -f ${GPAGE} ${GPAGE}~

# resize and watermark photos first
# if you want to keep original size
# remove line starting with -resize
echo -n "* Preparing picures... "
find . -maxdepth 1 -type f -iname "*.jpg" | \
sed 's,^\./,,' | sort | while read file; do convert $file \
-resize x${RSHEI} \
-gravity southeast -fill rgba\(0,0,0,0.4\) -annotate 0 "${WMARK}" \
${PWD}/${WDNAM}/${file}; done
echo "done."

# go to galery directory
cd ${PWD}/${WDNAM}

# opening xhtml code of galery page...
cat > ${GPAGE} << EOF
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
       "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">

<head>
   <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
   <meta name="GENERATOR" content="bashpic.sh" />
   <meta name="Description" content="${GNAME}" />
   <title>${GNAME}</title>
   <style type="text/css">
      img { border: 1pt; }
      body { background: white; color: black;
             font-family: sans-serif, Arial, Helvetica;
             font-size: 9pt; margin: 5pt; }
      h2 { color: black; background: white; font-size: 14pt; }
      a { text-decoration: none; }
      td.center { text-align: center; }
      td.nowrap { white-space: nowrap; }
      blockquote.center { text-align: center; }
   </style>
</head>

<body>

<table border="0" width="100%"><tr><td>
<h2>${GNAME}</h2></td>
<td align="right">generated by <a href="https://github.com/yradunchev/bashpic.sh">bashpic.sh</a> based on
<a href="http://sam.zoy.org/projects/unix/genethumb.html">genethumb.sh</a>
</td></tr></table>

<hr />

<table cellspacing="5" border="0">
  <tr>
EOF
# counter for table cols.
TCELL=0
# start processing photos...
find . -maxdepth 1 -type f -iname "*.jpg" | sed 's,^\./,,' | sort | while read FILE
do
	echo -n "* Processing ${FILE}... "
	# get EXIF date and time photo was taken as label for the thumbnail.
	LABEL=$(identify -format "%[exif:DateTimeOriginal]" ${FILE})
	# no EXIF info? then take file name as label for the thumbnail.
	[ -z "${LABEL}" ] && [ "${LABEL+xxx}" = "xxx" ] && LABEL=${FILE}
	# thumbnail file name.
	THUMB="${THDIR}/tn_${FILE%????}.png"
	# create thumbnail.
	[ -f "${THUMB}" ] || convert -geometry ${THWID}x${THHEI} "${FILE}" "${THUMB}" >/dev/null 2>&1
	# get dimensions and file size of the original photo.
	read OPDIM PSIZE << EOF
	$(identify -format '%wx%h %b' "${FILE}")
EOF
	# get dimensions of the generated thumbnail.
	THDIM=$( identify -format '%wx%h' "${THUMB}" )
	# add thumbnail to galery page.
	cat >> ${GPAGE} << EOF
      <td align="center">
        <a href="${FILE}"><img alt="${FILE} (${OPDIM})"
        width="`echo ${THDIM} | cut -f1 -dx`"
        height="`echo ${THDIM} | cut -f2 -dx`"
        src=".tpics/tn_${FILE%????}.png" /><br />${LABEL}<br />${OPDIM} (${PSIZE})</a>
      </td>
EOF
	# count cols. move to new row if needed.
	TCELL="`expr 0${TCELL} + 1`"
	[ x"${TCELL}" = "x${THCOL}" ] && echo "  </tr><tr>" >> ${GPAGE} && TCELL=0
	echo "done."
done
# closing xhtml code of galery page.
cat >> ${GPAGE} << EOF
  </tr>
</table>

</body>
</html>
EOF
echo "* All done."
